WindowState:
- [ceed515a-8d17-4e97-983b-046696c7d51f,0,false,2,1378,246,265,294,0,0]
- [2de8ec9f-ba13-41a7-81b0-c2f75f69c81d,1,true,1,1137,4,529,577,planningview,7.2568710083007808,-9.7653895072937011,19.188327789306641]
- [cae40103-9998-4f70-af7b-d7935177d93e,2,true,1,0,4,1127,732,modelingview,53.883363797077166,-338.166660952083,184.1594853149513,0.959931088596882,0.1308996938995686]
ActiveTab: 2
IsMaximized: false
OpenFolders:
- 33391e41-c9d3-46b4-ae0d-a3ad45168c13
- cdde81cd-4f40-42e0-bfea-fd86fd30f55c
- 29839f35-0ca2-4ab1-954f-15483b25fc1c
NumberOfObjects: 490
ModelHash: "1161af3059b08633d83c9e7f5a1a14705f0c05b63a70a55fb6269e3debe3e3c84ae4f5bff2141be5ac0bd406660f52e35aeb4447c44e6c8ba5697e0a57da7d1a"
